TWITCH_CLIENT_ID = "TWITCH_CLIENT_ID_HERE"
TWITCH_CLIENT_SECRET = "TWITCH_CLIENT_SECRET_HERE"
TWITCH_CHANNEL_NAME = "TWITCH_CHANNEL_NAME_HERE"
DISCORD_WEBHOOK_URL = "DISCORD_WEBHOOK_URL_HERE"
CHECK_INTERVAL_SECONDS = 30
CLIP_LOOKBACK_MINUTES = 2